#!/bin/bash

premake4 $@

if [[ -f Makefile ]]; then
	sed -i \
		-e 's/lib_core:/& | igen/' \
		-e 's/app_script_host_lib:/& | lib_core/' \
		-e 's/app_script_host:/& | app_script_host_lib/' \
		-e 's|\-f app_script_host\.make$|& -W src/quanta/app_script_host/main.cpp|' \
		-e 's/clean:/&:/' \
		-e '$a include scripts/tests.make' \
		Makefile
fi
